name:                ixy
version:             0.1.0.0
-- synopsis:
-- description:
homepage:            https://github.com/githubuser/ixy#readme
license:             BSD3
license-file:        LICENSE
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
build-type:          Simple
extra-source-files:  README.md
cabal-version:       >=1.10

library
  hs-source-dirs:      src
  ghc-options:         -Wall
  exposed-modules:     Ixgbe
  other-modules:       Ixgbe.Pci, Ixgbe.Memory, Ixgbe.Queue
  build-depends:       base >= 4.7 && < 5
                     , array >= 0.5 && <= 0.6
                     , binary >= 0.8.0.0 && <= 0.10.0.0
                     , bytestring >= 0.10 && <= 0.13
                     , ghc-prim >= 0.5 && < 0.13
                     , pathtype >= 0.8 && <= 0.8.1.3
                     , text >= 1.2 && <= 2.1.3
                     , vector >= 0.12.0.1 && < 0.14
                     , unix >= 2.7.0.0 && <= 2.8.8.0
                     , unix-memory >= 0.1.1 && <= 0.1.2
  default-language:    Haskell2010
  default-extensions:  OverloadedStrings, FlexibleContexts, BangPatterns

executable forwarder 
  hs-source-dirs:      app
  main-is:             Forwarder.hs
  ghc-options:         -Wall
  build-depends:       base
                     , bytestring >= 0.10 && <= 0.13
                     , clock >= 0.7 && < 0.9
                     , ixy
                     , text >= 1.2 && <= 2.1.3
                     , unix >= 2.7.0.0 && <= 2.8.8.0
  default-language:    Haskell2010
  default-extensions:  OverloadedStrings, FlexibleContexts, BangPatterns

source-repository head
  type:     git
  location: https://github.com/githubuser/ixy
